INSERT INTO 
    TST (
        PID,
        ID,
        PT,
        GR,
        DT,
        -- CL,
        -- RS,
        -- SS,
        GE,
        PC,
        -- OT,
        -- ST,
        -- CE,
        TD,
        -- PR,
        PL,
        -- RU,
        TA,
        SQ,
        SCL,
        -- SRC,
        TY,
        IDT,
        IUI,
        IUN,
        -- UUI,
        -- UUN,
        -- LX,
        -- QT,
        -- PI,
        -- PA1,
        -- PA2,
        -- PA3,
        -- ELP,
        DTS
    ) VALUES (
        :PID,
        :ID,
        :PT,
        :GR,    
        :DT,
        -- :CL,
        -- :RS,
        -- :SS,
        :GE,
        :PC,
        -- :OT,
        -- :ST,
        -- :CE,
        :TD,
        -- :PR,
        :PL,
        -- :RU,
        :TA,
        :SQ,
        :SCL,
        -- :SRC,
        :TY,
        GETDATE(),
        :IUI,
        :IUN,
        -- :UUI,
        -- :UUN,
        -- :LX,
        -- :QT,
        -- :PI,
        -- :PA1,
        -- :PA2,
        -- :PA3,
        -- :ELP,
        GETDATE()
    )